spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=EEIT40Project
    username: sa
    password: Passw0rd!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  profiles:
    active: dev, fast
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8080